FROM alpine:3.21

RUN apk add --no-cache git && \
    adduser -D runner -u 1001

COPY instapaper-collector /usr/local/bin/instapaper-collector

USER runner

ENTRYPOINT ["/usr/local/bin/instapaper-collector"]
